codecov:
  require_ci_to_pass: yes

ignore:
  - "internal/tools/*"

coverage:
  precision: 1
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 40%
        threshold: 0.5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: yes
