name: Go

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Cache Go Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.mod') }}
      - name: Install tools
        if: steps.tool-cache.outputs.cache-hit != 'true'
        run: make install-tools
      - name: Add Permissions to Tool Binaries
        run: chmod -R +x ~/go/bin
      - name: Check
        run: make ci-check

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Cache Go Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-${{ hashFiles('**/go.mod') }}
      - name: Run Unit Tests
        run: make test
        
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Cache Go Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-${{ hashFiles('**/go.mod') }}
      - name: Run Unit Tests
        run: make test
        
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Cache Go Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: /Users/runneradmin/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.mod') }}
      - name: Run Unit Tests
        run: make test
          
