name: Go

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:

  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Setup Go Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Cache Go Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: /home/runner/go/pkg/mod
          key: go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod') }}
      - name: Restore tools binaries
        id: tool-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-tool-binaries
        with:
          path: /home/runner/go/bin
          key: tools-${{ runner.os }}-${{ hashFiles('/home/runner/go/bin') }}
      - name: Install tools
        if: steps.tool-cache.outputs.cache-hit != 'true'
        run: make install-tools
      - name: Upload Tool Binaries
        uses: actions/upload-artifact@v1
        with:
          name: tool-binaries
          path: /home/runner/go/bin

  lint:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Cache Go Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: /home/runner/go/pkg/mod
          key: go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod') }}
      - name: Download Tool Binaries
        uses: actions/download-artifact@v1
        with:
          name: tool-binaries
          path: /home/runner/go/bin
      - name: Add Permissions to Tool Binaries
        run: chmod -R +x /home/runner/go/bin
      - name: Vet
        run: make vet
      - name: Lint
        run: make lint

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Cache Go Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: /home/runner/go/bin
          key: go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod') }}
      - name: Run Unit Tests
        run: make test
        
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Cache Go Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: /home/runner/go/bin
          key: go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod') }}
      - name: Run Unit Tests
        run: make test
        
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Cache Go Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: /Users/runneradmin/go/pkg/mod
          key: go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod') }}
      - name: Run Unit Tests
        run: make test
          
