name: Run CodeCov
on:
  push:
    branches:
      - main
  pull_request:
env:
  # Path to where test results will be saved.
  TEST_RESULTS: /tmp/test-results
  # Default minimum version of Go to support.
  DEFAULT_GO_VERSION: 1.15
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ env.DEFAULT_GO_VERSION }}
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - name: Module cache
      uses: actions/cache@v2.1.6
      env:
        cache-name: go-mod-cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
    - name: Run coverage tests
      run: |
        make test-coverage
        mkdir $TEST_RESULTS
        cp coverage.out $TEST_RESULTS
        cp coverage.txt $TEST_RESULTS
        cp coverage.html $TEST_RESULTS
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        fail_ci_if_error: true
        verbose: true
    - name: Store coverage test output
      uses: actions/upload-artifact@v2
      with:
          name: opentelemetry-log-collection-test-output
          path: ${{ env.TEST_RESULTS }}
